//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentDevice
    {
        public int Id { get; set; }
        public string AgentId { get; set; }
        public string AppKey { get; set; }
        public string DeviceId { get; set; }
        public string DeviceMode { get; set; }
        public string PlaceOfOperation { get; set; }
        public string OperationGpsLocation { get; set; }
        public string Status { get; set; }
        public Nullable<bool> OnlineStatus { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string Password { get; set; }
    }
}
