//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CallAndPayDbContext : DbContext
    {
        public CallAndPayDbContext()
            : base("name=CallAndPayDbEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgentDevice> AgentDevices { get; set; }
        public virtual DbSet<AgentMerchant> AgentMerchants { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerAccount> CustomerAccounts { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<NextOfKin> NextOfKins { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }

        //public System.Data.Entity.DbSet<BLL.TransactionViewModel> TransactionViewModels { get; set; }

        //public System.Data.Entity.DbSet<BLL.NextOfKinViewModel> NextOfKinViewModels { get; set; }

        ///public System.Data.Entity.DbSet<BLL.NextOfKinViewModel> NextOfKinViewModels { get; set; }

        //public System.Data.Entity.DbSet<BLL.AccountViewModel> AccountViewModels { get; set; }

        //public System.Data.Entity.DbSet<BLL.CustomerViewModel> CustomerViewModels { get; set; }
    }
}
