//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int Id { get; set; }
        public string DeviceMacAddress { get; set; }
        public string OSType { get; set; }
        public string OSVersion { get; set; }
        public string IMEINumber { get; set; }
        public Nullable<bool> HasCardReader { get; set; }
        public Nullable<bool> HasCamera { get; set; }
        public Nullable<bool> HasPrinter { get; set; }
        public Nullable<bool> HasNFC { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
    }
}
